apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assetmanager-ingress
  namespace: assetmanager
spec:
  rules:
    - host: assetmanager.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assetmanager-web
                port:
                  number: 80
