apiVersion: v1
kind: Service
metadata:
  name: assetmanager-postgres
  namespace: assetmanager
spec:
  selector:
    app: assetmanager-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
