apiVersion: v1
kind: Secret
metadata:
  name: assetmanager-secret
  namespace: assetmanager
type: Opaque
stringData:
  POSTGRES_USER: inventory
  POSTGRES_PASSWORD: inventory
  POSTGRES_DB: inventory
  SECRET_KEY: change-this-to-a-strong-secret
